using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GV_Testing_Program_2
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private const string quickScore = "Quickscore for \nParent/Teacher Forms",
            newTester = "New Tester",
            showResults = "Show Results",
            advancedSearch = "Advanced Search Options",
            basicSearch = "Basic Search",
            refresh = "Refresh",
            delete = "Delete";


        public MainWindow()
        {
            InitializeComponent();

            QuickScoreButton.Content = quickScore;
            TakeTestButton.Content = newTester;
            showResultsButton.Content = showResults;
            ToggleAdvancedSearchButton.Content = advancedSearch;
            RefreshButton.Content = refresh;
            DeleteButton.Content = delete;


            firstNameCheckBox.Visibility = Visibility.Hidden;
            middleNameCheckBox.Visibility = Visibility.Hidden;
            lastNameCheckBox.Visibility = Visibility.Hidden;

            if (!Directory.Exists(K.testerProfilesDirectory))
            {
                Directory.CreateDirectory(K.testerProfilesDirectory);
            }
        }

        /*Button Click Method*/
        private void button_Clicked(object sender, RoutedEventArgs e)
        {

            Button? btn = sender as Button;
            string txt = !(btn is null) ? (string)btn.Content : "";
            //MessageBox.Show(txt);

            switch (txt)
            {
                case quickScore:
                    //QuickScore Button's Actions go here
                    break;
                case newTester:
                    //new tester window should open here
                    new TesterInfoWindow().Show();
                    break;
                case showResults:
                    //Take the show results window from the BAARS program and modify it for use here
                    break;
                case advancedSearch:
                case basicSearch:
                    //this will just call a function that toggles first, middle, last name checkbox visibility
                    toggleAdvancedSearch();
                    break;
                case refresh:
                    //Toggles the reloadTable() function
                    break;
                case delete:
                    //For removing items from the list
                    break;
                default:
                    return;
            }
        }



        //This one seems pretty self-explanatory
        private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
        {

        }

        /*checkbox checked methods... probably a better way to do this*/

        //Might not be able to get away with the same thing as before... but maybe
        private void checkboxChecked(object sender, RoutedEventArgs e)
        {

        }

        private void LastName_Checked(object sender, RoutedEventArgs e)
        {

        }

        private void FirstName_Checked(object sender, RoutedEventArgs e)
        {

        }

        private void MiddleName_Checked(object sender, RoutedEventArgs e)
        {

        }

        /*Table Generation Methods*/

        // Runs upon automatically generating collumns used to formate table
        // https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid_guidance/customize_autogenerated_columns

        private void Table_AutoGenerateColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {

            if (e.Column.Header.ToString() == "LastName")
            {
                e.Column.Width = 100;
            }
            else if (e.Column.Header.ToString() == "MiddleName")
            {
                e.Column.Width = 100;
            }
            else if (e.Column.Header.ToString() == "FirstName")
            {
                e.Column.Width = 100;
            }
            else if (e.Column.Header.ToString() == "Age")
            {
                e.Column.Width = 30;
            }
            else if (e.Column.Header.ToString() == "Gender")
            {
                e.Column.Width = 50;
            }
            else if (e.Column.Header.ToString() == "Path")
            {
                e.Column.Width = 364;
            }
        }

        private void Table_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {

        }

        /*Helper Fucntions*/
        private void toggleAdvancedSearch()
        {
            if (!firstNameCheckBox.IsVisible)
            {
                firstNameCheckBox.Visibility = Visibility.Visible;
                middleNameCheckBox.Visibility = Visibility.Visible;
                lastNameCheckBox.Visibility = Visibility.Visible;
                ToggleAdvancedSearchButton.Content = basicSearch;
            }
            else
            {
                firstNameCheckBox.Visibility = Visibility.Hidden;
                middleNameCheckBox.Visibility = Visibility.Hidden;
                lastNameCheckBox.Visibility = Visibility.Hidden;
                firstNameCheckBox.IsChecked = true;
                middleNameCheckBox.IsChecked = true;
                lastNameCheckBox.IsChecked = true;
                ToggleAdvancedSearchButton.Content = advancedSearch;
            }
        }
    }
}
